app:
  external_stylesheet: bootstrap # Options: bootstrap, none
  max_uploaded_files: 10         # Max number of files allowed
  host: "0.0.0.0"                # Server host
  port: 8709                     # Server port

style:
  padding: "10px"
  margin: auto
  max_width: 600
  font_family: "Arial, sans-serif"
  upload_height: 120
  upload_border_color: "#ECF0F1"
  header_text_color: "#2C3E50"
